spring:
    data.redis:
        host: localhost
        password: SuperSecretRedisPassword
        port: 6379
    application:
        name: spring-redis-reactive-websocket
management:
    endpoint:
        health:
            enabled: true
            show-details: always
