FROM maven:3.8.8-eclipse-temurin-17 as build
WORKDIR /app
COPY ../../.. ./
RUN mvn clean package --file pom.xml

FROM eclipse-temurin:17-jdk-jammy
ENV RUNTIME_PLATFORM=JVM
COPY --from=build /app/target/spring-redis-websocket-*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
