version: '3.2'
services:
    nginx:
        image: rawsanj/nginx-lb
        ports:
            - "80:80"
        depends_on:
            - spring-chat-1
            - spring-chat-2
            - spring-chat-3
    redis:
        image: bitnami/redis:7.2.3
        environment:
            - REDIS_PASSWORD=SuperSecretRedisPassword
        ports:
            - "6379:6379"
        volumes:
            - 'redis_data:/bitnami/redis/data'
    spring-chat-1:
        image: rawsanj/spring-redis-websocket:3.0.1-webflux
        environment:
            - SPRING_DATA_REDIS_HOST=redis
            - SPRING_DATA_REDIS_PASSWORD=SuperSecretRedisPassword
        ports:
            - "8080"
        depends_on:
            - redis
    spring-chat-2:
        image: rawsanj/spring-redis-websocket:3.0.1-webflux
        environment:
            - SPRING_DATA_REDIS_HOST=redis
            - SPRING_DATA_REDIS_PASSWORD=SuperSecretRedisPassword
        ports:
            - "8080"
        depends_on:
            - redis
    spring-chat-3:
        image: rawsanj/spring-redis-websocket:3.0.1-webflux
        environment:
            - SPRING_DATA_REDIS_HOST=redis
            - SPRING_DATA_REDIS_PASSWORD=SuperSecretRedisPassword
        ports:
            - "8080"
        depends_on:
            - redis
volumes:
    redis_data:
        driver: local
